typography_spectrum: 0.99915
color:
  brandColors:
    - '#231f20'
    - '#e79200'
    - '#ffffff'
    - '#a43100'
    - '#ffff00'
  brandStrength: 0.25
  lightness: 0.02168650575913489
  saturation: 0.3125
  rhythmicContrast: 0.7566835444886237
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2094
analytics:
  google: null
  facebook: null
  twitter: null
name: Victory Design
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: WEBSITE SOLUTIONS
description: A Great Website Starts with a Great Website Solution
purpose: []
