name: Victory Design
favicon: null
layout_spectrum: 0.90004
typography_spectrum: 0.99915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#e79200'
    - '#ffffff'
    - '#a43100'
    - '#ffff00'
  brandStrength: 0.25
  lightness: 0.02168650575913489
  saturation: 0.3125
  rhythmicContrast: 0.7566835444886237
purpose: []
